//let refresh = document.querySelector("input");

//var refresh = window.getElementById("refresh");
//refresh.addEventListener("click", location.reload() false);

// Fonction pour faire disparaître le texte
let special = document.querySelectorAll("p")[0];

special.addEventListener("mouseover", function() {
    special.classList.toggle("surprise");
});

});
// Fonction pour rafraîchir la page en cliquant sur "Envoyer"
function refreshpage(){
    window.location.reload();
});
let Show = document.querySelector("#button");

Show.addEventListener("click", function() {
    Show.classList.toggle("special");
});
// Fonction de boucle
let th = prompt("Combien ?");
while (th.() <="10") {
    th = prompt("Ca va, tu n'en abuses pas"); 
}   
console.log("Tu exagères ! Tu vas avoir mal aux dents !");

let input = 'Combien';

while (i <=10) {
    input = prompt("Trop c'est trop !");
}
alert ("Ca va, tu n'en abuses pas");